apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: skaffold
deploy:
  kubectl:
    manifests:
      - "./infra/k8s/*"
build:
  local:
    push: false
  artifacts:
    - image: v0x12/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "./src/*.ts"
            dest: .
    - image: v0x12/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "./src/*.ts"
            dest: .
    - image: v0x12/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "./src/*.ts"
            dest: .
    - image: v0x12/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "./*.js"
            dest: .
